<?xml version="1.0" encoding="utf-8"?><Database Name="master" Class="ResumeObjectsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-5P9JLMHT\SQLEXPRESS;Initial Catalog=master;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="masterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ResumeObjects" Member="ResumeObjects">
    <Type Name="ResumeObject">
      <Column Name="ObjectType" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>